[build]
  base = "ai_agents/agents/examples/voice-assistant-live2d/frontend"
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/api/token/*"
  to = "https://api.theten.ai/token/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/api/agents/*"
  to = "https://api.theten.ai/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/"
  to = "/live2d"
  status = 301
  force = true

[[redirects]]
  from = "/*"
  to = "/live2d"
  status = 200
  force = true

[[headers]]
  for = "/api/*"
  [headers.values]
    Cache-Control = "no-store"
